name = "JuliaMVMCWorkspace"
authors = ["Takahiro Misawa <tmisawa@issp.u-tokyo.ac.jp>"]
version = "0.0.0"

[deps]
MVMCOptimizers = "3516085a-728f-4003-a487-32232985ade4"
MVMCExpertModeParsers = "f8463493-42a4-4c1a-8bf4-93a3cbd844bc"
PfaPack = "fb1811a7-9b9e-407c-aa55-948d91a1aed1"
SFMT = "f01bd734-aebb-490b-aa9b-8490e8eb2402"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
MVMCOptimizers = {path = "MVMCOptimizers.jl"}
MVMCExpertModeParsers = {path = "MVMCExpertModeParsers.jl"}
PfaPack = {path = "PfaPack.jl"}
SFMT = {path = "SFMT.jl"}

[compat]
julia = "1.11"
