using Logging
using MVMCExpertModeParsers: ExpertModeData, ModParaParameters, OrbitalTerm

function slater_checked_test_data()
    data = ExpertModeData()
    data.modpara = ModParaParameters(nsite=2, nelec=1, nsp_gauss_leg=1, nmp_trans=1)
    data.n_qp_trans=1; data.n_qp_opt_trans=1
    data.qp_trans=[[0,1]]; data.qp_trans_inv=[[0,1]]; data.qp_trans_sgn=[[1,1]]
    data.orbital_terms=[
        OrbitalTerm(0,0,0,1+2im,true,1), OrbitalTerm(0,1,1,2+4im,true,-1),
        OrbitalTerm(1,0,2,3+6im,true,1), OrbitalTerm(1,1,3,4+8im,true,1),
    ]
    data.orbital_sgn=[1 -1;1 1]
    weights=MVMCExpertModeParsers.QuantumProjectionWeights()
    weights.spgl_cos=ComplexF64[1]
    weights.spgl_cos_sin=ComplexF64[.25]
    weights.spgl_cos_cos=ComplexF64[.5]
    weights.spgl_sin_sin=ComplexF64[.125]
    data.qp_weights=weights
    return data
end

function slater_checked_capture(f,data,state)
    try
        f(data,state)
        return nothing
    catch error
        return typeof(error)
    end
end

@testset "unit/slater checked serial kernel" begin
    data=slater_checked_test_data()
    state=MVMCOptimizers.VMCOptimizationState(2,1,1,1,1,1,false,false)
    fill!(state.slater_matrix.slater_elm_real,77)
    MVMCOptimizers.update_slater_elm_fcmp!(data,state)
    # Independent dyadic evaluation of C slater.c four complex blocks, using
    # (cs,cc,ss)=(1/4,1/2,1/8), identity maps, and OrbitalSgn[0,1]=-1.
    # For pair(0,1), a=-2-4i,b=3+6i; no fixture generated by this kernel.
    expected=ComplexF64[
        0 1.25+2.5im .625+1.25im -.625-1.25im;
        -1.25-2.5im 0 1.25+2.5im 2.5+5im;
        -.625-1.25im -1.25-2.5im 0 -1.25-2.5im;
        .625+1.25im -2.5-5im 1.25+2.5im 0;
    ]
    actual=transpose(reshape(state.slater_matrix.slater_elm,4,4))
    # Each value involves at most three exactly dyadic complex products/adds;
    # 8eps accommodates portable operator lowering without changing any fixture.
    @test maximum(abs,actual-expected) <= 8eps(Float64)*(1+maximum(abs,expected))
    @test all(==(77),state.slater_matrix.slater_elm_real) # mirror publication remains caller-owned
    MVMCOptimizers.copy_complex_realpart!(state.slater_matrix.slater_elm_real,
        state.slater_matrix.slater_elm,16;threaded=false)
    @test maximum(abs,transpose(reshape(state.slater_matrix.slater_elm_real,4,4))-real.(expected)) <= 8eps(Float64)*(1+maximum(abs,expected))

    scenarios=(
        d->(d.qp_weights=nothing),
        d->(d.qp_weights=1),
        d->empty!(d.qp_weights.spgl_cos),
        d->empty!(d.qp_weights.spgl_cos_sin),
        d->empty!(d.qp_weights.spgl_cos_cos),
        d->empty!(d.qp_weights.spgl_sin_sin),
        d->resize!(d.qp_trans_sgn[1],1),
        d->resize!(d.qp_trans[1],1),
        d->(d.qp_trans[1][1]=-1),
        d->(d.qp_opt_trans=[[0,2]]; d.qp_opt_trans_sgn=[[1,1]]),
        d->(d.orbital_terms[2].idx=-1),
        d->empty!(d.qp_trans),
    )
    for mutate in scenarios
        original_data=slater_checked_test_data(); mutate(original_data)
        checked_data=deepcopy(original_data)
        original=MVMCOptimizers.VMCOptimizationState(2,1,1,1,1,1,false,false)
        checked=deepcopy(original)
        fill!(original.slater_matrix.slater_elm,19-7im)
        fill!(checked.slater_matrix.slater_elm,19-7im)
        a=with_logger(NullLogger()) do
            slater_checked_capture(MVMCOptimizers._update_slater_elm_fcmp_reference!,original_data,original)
        end
        b=with_logger(NullLogger()) do
            slater_checked_capture(MVMCOptimizers.update_slater_elm_fcmp!,checked_data,checked)
        end
        @test a === b
        @test maximum(abs,original.slater_matrix.slater_elm-checked.slater_matrix.slater_elm) <= 8eps(Float64)*(1+maximum(abs,original.slater_matrix.slater_elm))
    end
    for capacity in (0,1,7,15)
        original=MVMCOptimizers.VMCOptimizationState(2,1,1,1,1,1,false,false)
        checked=deepcopy(original)
        resize!(original.slater_matrix.slater_elm,capacity)
        resize!(checked.slater_matrix.slater_elm,capacity)
        MVMCOptimizers._update_slater_elm_fcmp_reference!(data,original)
        MVMCOptimizers.update_slater_elm_fcmp!(data,checked)
        @test isempty(original.slater_matrix.slater_elm) || maximum(abs,original.slater_matrix.slater_elm-checked.slater_matrix.slater_elm) <= 8eps(Float64)*(1+maximum(abs,original.slater_matrix.slater_elm))
    end
    log=IOBuffer()
    with_logger(SimpleLogger(log,Debug)) do
        MVMCOptimizers.update_slater_elm_fcmp!(data,state)
    end
    @test occursin("first 5 orbital_terms",String(take!(log)))
    @test maximum(abs,transpose(reshape(state.slater_matrix.slater_elm,4,4))-expected) <= 8eps(Float64)*(1+maximum(abs,expected))
end
